POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI4Mzg1NDkwLCJ1c2VySWQiOjJ9.VKasw0GrxJnp34sjd6F40xinC8YJoQXU5pGeCXVq2LU